### ISSUE TITLE
Align reads

### ISSUE THREAD

**Issue by DHGK** [fmicompbio/eisaR#28] opened 2020-11-02 21:01 UTC
Hi,

Great software and thanks for sharing!

As I'm following the Bioconductor tutorial, I have some difficulties understand section 4.1 Align reads (I'm new to such bioinformatics and trying to learn more). Specifically, I wonder what data do I need to use as inputs for: 

sampleFile <- "extdata/samples_chip_single.txt"
genomeFile <- "extdata/hg19sub.fa"
proj <- qAlign(sampleFile = "extdata/samples_rna_single.txt", 
               genome = "extdata/hg19sub.fa",
               aligner = "Rhisat2", splicedAlignment = TRUE)

Following section3, I've prepared annotation with EnsDb and got fastq for my rna seq. However, I don't quite understand what should I put for sampleFile and genomeFile. I'm dealing with human sample. I sincerely I could get helped with this.

Thanks in advance!

**Comment by csoneson** [comment] 2020-11-03 19:59
Hi @DHGK,

to understand the alignment part better, I would recommend to take a look at the vignette for the [QuasR](https://www.bioconductor.org/packages/QuasR/) package (which is used to perform the alignment in the vignette). In particular, `genomeFile` points to a fasta file with the genomic sequence that you want to align to (in the example above, it is a subset of `hg19`). The `sampleFile` lists the samples and the paths to the fastq files. This is described further in [section 5.1](https://www.bioconductor.org/packages/release/bioc/vignettes/QuasR/inst/doc/QuasR.html#sampleFile) of the `QuasR` vignette.

**Comment by DHGK** [comment] 2020-11-03 20:09
Hi,

Thanks a lot for your reply! I tried to let the variables point to my files, but here's an error that I got:

Error: MN1_18a_Scr-kd_R1.fq.gz MN1_18a_Scr-kd_R2.fq.gz MN1_18a_Scr_kd listed in samples_dat.txt does not exist

The txt sampleFile is in the same directory as all my sample fastq.gz -- I don't really understand what the error mean

**Comment by csoneson** [comment] 2020-11-03 20:16
Is `samples_dat.txt` tab-delimited? Can you paste the content of the file?

**Comment by DHGK** [comment] 2020-11-03 20:18
Yes, here's my file:

FileName1	FileName2	SampleName
MN1_18a_Scr-kd_R1.fq.gz MN1_18a_Scr-kd_R2.fq.gz MN1_18a_Scr_kd
MN1_18a_UPF1-kd_R1.fq.gz MN1_18a_UPF1-kd_R2.fq.gz MN1_18a_UPF1_kd
MN2_18a_Scr-kd_R1.fq.gz MN2_18a_Scr-kd_R2.fq.gz MN2_18a_Scr_kd
MN2_18a_UPF1-kd_R1.fq.gz MN2_18a_UPF1-kd_R2.fq.gz MN2_18a_UPF1_kd
MN6_18a_Scr-kd_R1.fq.gz MN6_18a_Scr-kd_R2.fq.gz MN6_18a_Scr_kd
MN6_18a_UUP1-kd_R1.fq.gz MN6_18a_UUP1-kd_R2.fq.gz MN6_18a_UPF1_kd

**Comment by csoneson** [comment] 2020-11-03 20:22
The error message you get suggests to me that the file is not actually tab-delimited (it seems to consider `MN1_18a_Scr-kd_R1.fq.gz MN1_18a_Scr-kd_R2.fq.gz MN1_18a_Scr_kd` as a single word). Can you try to read it with 

```
res <- read.delim("samples_dat.txt", header = TRUE, sep = "\t")
```

and see how many columns you get? If the file is tab-delimited, you should get three columns.

**Comment by DHGK** [comment] 2020-11-03 20:27
Thanks a lot!! It's indeed not tab-delimited. I regenerated the table and seemed to fix the problem!

**Comment by csoneson** [comment] 2020-11-04 08:50
I'll close this issue since it seems that the problem is solved.

**Closed by csoneson** 2020-11-04 08:50 UTC
