### ISSUE TITLE
I have a "Negative counts not allowed" issue.

### ISSUE THREAD

**Issue by dongminshion** [fmicompbio/eisaR#35] opened 2022-08-01 10:23 UTC
Hi Sir,

First of all, I would like to apologize for my poor English skills.

I have a question about eisaR. First of all, I am going to apply eisaR to our pipeline. So, I imported a database from EnsDB to maintain the same conditions as the parameters I used.

" ah <- AnnotationHub() 
query(ah, "EnsDb") 
ahDb <- query(ah, pattern = c("Homo Sapiens", "EnsDb", 99)) 
ahDb 
ahEdb <- ahDb[[1]] "

Then, Exon and gene body regions were extracted from the database using the getRegionsFromTxDb command.

"regS <- getRegionsFromTxDb(txdb = ahEdb, strandedData = TRUE)"

Afterwards, I extracted the gtf file to qunatify the reads the way I used to for the existing pipeline.

"export(regS$exons, "H_sapiens_ENS99_exons_stranded.gtf")\
export(regS$genebodies, "H_sapiens_ENS99_genebodies_stranded.gtf")"

After that, I was able to obtain genebody count and exon count by quantifying the reads of the example data I had using HTSeq(This is the quantifier I used in my pipeline).

"htseq-count -t sequence_feature -n 4 Control_1.bam Control_2.bam Case_1.bam Case_2.bam H_sapiens_ENS99_exons_stranded.gtf > counts_exon.txt
htseq-count -t sequence_feature -n 4 Control_1.bam Control_2.bam Case_1.bam Case_2.bam H_sapiens_ENS99_genebodies_stranded.gtf > counts_gb.txt"

After importing the read counts, like the steps of eisaR, I subtracted the exon count from the genebody count to get the intron count.

"cntEx <- read.delim("Practice/counts_exon.txt", row.names = 1)
cntGb <- read.delim("Practice/counts_gb.txt", row.names = 1)

column <- c("CT_1","CT_2","CS_1","CS_2")

colnames(cntEx) <- column
colnames(cntGb) <- column

cntIn <- cntGb - cntEx"

After adjusting the condition value, when entering the runEISA command line, the following error was encountered.

"cond <- factor(c("CT", "CT", "CS", "CS"))

res <- runEISA(cntEx, cntIn, cond)"

"> res <- runEISA(cntEx, cntIn, cond)
Error: Negative counts not allowed"

As a result of examining the data frame to find the cause, it was confirmed that the exon count in the gene causing the problem is higher than the genebody count.

gene | CT1 | CT2 | CS1 | CS2
ENSG00000254003 | 85 | 325 | 105 | 40   --> genebody count
ENSG00000254003 | 106 | 269 | 94 | 42   --> exon count

In the extracted gtf range, the genebody range clearly includes the exon range. So, in my opinion, it is impossible for exon count to represent higher than genebody count. Am I missing something while trying to use eisaR with an external tools? Thank you for reading. I would be happy if I could ask for your advice on solving this problem.

Shin.

**Comment by csoneson** [comment] 2022-08-02 13:10
Hi Shin,

this indeed seems strange. I am not sure that the issue is strictly on the `eisaR` side, since, as you say, the exon coordinates in the exported gtf file indeed are contained within those of the genebody, as expected. Thus, since the gene you mention above does not overlap any other feature, I would also typically expect the genebody count to be larger than the exon count (unless, for example, for some reason, the reads that are spliced and span both exons end up being counted twice, or if there are other interactions with surrounding genes). A few things that you could try to track down the cause: 

* `htseq-count` by default aggregates by the `gene_id` annotation for the features in the gtf file. The gtf file you have exported does not have that annotation (please correct me if I'm wrong). Could you try to specify `-i ID` when calling `htseq-count` (at least that's what I get in my gtf file if I run your code above)? 
* Look at the alignments in a genome browser to perhaps figure out what might be happening.
* Use the `-o` argument of `htseq-count` to export a sam file with the assignment for each read, and look in more detail at the reads that end up being assigned to the exons of `ENSG00000254003`, but not to the genebody.
* Make two tiny gtf files that just contain the records for the `ENSG00000254003` gene (exons and genebody, respectively), and run `htseq-count` again to see if you get the same results.
* There is another gene close to `ENSG00000254003`, and I'm just wondering if by chance some read (pair) will map partly to the gene of interest and partly to intronic regions of the neighboring gene. You would see this e.g. in the genome browser as well.
* You could also try another counting approach, e.g. `Rsubread::featureCounts()` or `QuasR::qCounts()` to see if the issue persists.

Could you also let us know the versions of the packages that you are using (in particular, `eisaR` and `htseq-count`)?

Hope this helps,
Charlotte

**Comment by csoneson** [comment] 2022-12-18 14:52
Closing due to inactivity - feel free to reopen if the problem persists.

**Closed by csoneson** 2022-12-18 14:52 UTC
